name: quickJS build

on: workflow_dispatch

jobs:
    build:
        name: Build quickJS for ${{ matrix.platform }}
        strategy:
            matrix:
                platform: [ubuntu-18.04, macos-10.15]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 1
            - name: Build quickJS linux
              if: matrix.platform == 'ubuntu-18.04'
              run: cd 3rdparty/quickjs && make
            - name: Add linux lib
              if: matrix.platform == 'ubuntu-18.04'
              run: cd 3rdparty/quickjs && cp libquickjs.lto.a ../libs/quickjs/linux/x86_64/libquickjs.a
            - name: Build quickJS MacOS
              if: matrix.platform == 'macos-10.15'
              run: cd 3rdparty/quickjs && make
            - name: Add MacOS lib
              if: matrix.platform == 'macos-10.15'
              run: cd 3rdparty/quickjs && cp libquickjs.lto.a ../libs/quickjs/darwin/x86_64/libquickjs.a
            - name: Create PR
              uses: peter-evans/create-pull-request@v3
              with:
                commit-message: Update quickJS static library for ${{ matrix.platform  }}
                branch: quickJS-lib
                branch-suffix: random
                delete-branch: true
                title: quickJS static library for ${{ matrix.platform  }}
                body: Auto-generated pull request to build quickJS for ${{ matrix.platform  }}

